### ISSUE TITLE
Latest build fails

### ISSUE THREAD

**Issue by githubbbie** [tiirex9/linkr-docker#1]
First, thanks for this package. I am trying now...

Anyone tried a build lately? I'm trying on my server running alpine 3.11 using latest docker...should just work, right?

```
Pulling mysql (mariadb:)...
latest: Pulling from library/mariadb
5c939e3a4d10: Pull complete                                                              
c63719cdbe7a: Pull complete                                                              
19a861ea6baf: Pull complete                                                              
651c9d2d6c4f: Pull complete                                                              
077e14009561: Pull complete                                                              
5f038f59a326: Pull complete                                                              
1b0216466f21: Pull complete                                                              
1b0570aa273a: Pull complete                                                              
37a3d332e397: Pull complete                                                              
c6d79b4558a5: Pull complete                                                              
02ee031466e7: Pull complete                                                              
4b07db1ea2c8: Pull complete                                                              
ae2075ab7b06: Pull complete                                                              
2055e2675cd5: Pull complete                                                              
Digest: sha256:57bd9e5d5931b27fd89c9c619e2449627e584dafa11a494742cb1a59825ae8ab
Status: Downloaded newer image for mariadb:latest
Creating thebandwork_mysql_1 ... done
Pulling linkr (tiirex9/linkr:)...
latest: Pulling from tiirex9/linkr
cd784148e348: Pull complete                                                              
3c1a9ba32ed5: Pull complete                                                              
ad2301f3cf66: Pull complete                                                              
cfb663da48b1: Pull complete                                                              
9f77f4d98c27: Pull complete                                                              
f8c4fc839a12: Pull complete                                                              
4d293807ae4f: Pull complete                                                              
a1995ab60eb2: Pull complete                                                              
dad0d2fa27d8: Pull complete                                                              
a0c4d0e9907f: Pull complete                                                              
Digest: sha256:c8bf65a30ac667f9d6c18948ea7407cc9f629d78a4852f8a4a09c1e2be927a75
Status: Downloaded newer image for tiirex9/linkr:latest

> linkr@1.0.0 build /linkr
> npm run generate-secret && npm run build-css && npm run build-js && npm run build-html

> linkr@1.0.0 generate-secret /linkr
> PYTHONPATH=. python scripts/generate_secret.py

Generated a new secret.

> linkr@1.0.0 build-css /linkr
> mkdir -p frontend/static/dist && node-sass --output-style compressed frontend/styles/ma
in.scss frontend/static/dist/main.css

Rendering Complete, saving .css file...
Wrote CSS to /linkr/frontend/static/dist/main.css

> linkr@1.0.0 build-js /linkr
> mkdir -p frontend/static/dist && webpack --config frontend/config/webpack

Hash: 5cb53467a0c4f1752d5d
Version: webpack 3.12.0
Time: 15148ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  507 kB       0  [emitted]  [big]  bundle
  [89] ./scripts/client.js + 67 modules 319 kB {0} [built]
 [159] ./resources/blobs/fonts/karla-bold.txt 23.8 kB {0} [built]
 [160] ./resources/blobs/fonts/karla-regular.txt 22.4 kB {0} [built]
 [161] ./resources/blobs/fonts/source-code-pro-medium.txt 41.1 kB {0} [built]
 [162] ./resources/blobs/fonts/source-code-pro-regular.txt 36.7 kB {0} [built]
    + 220 hidden modules

> linkr@1.0.0 build-html /linkr
> PYTHONPATH=. python scripts/build_html.py
/linkr/env/lib/python2.7/site-packages/raven/conf/remote.py:90: UserWarning: Transport se
lection via DSN is deprecated. You should explicitly pass the transport class to Client()
 instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass th
e transport class to Client() instead.')
Traceback (most recent call last):
  File "scripts/build_html.py", line 1, in <module>
    import linkr  # flake8: noqa: F401
  File "/linkr/linkr.py", line 7, in <module>
    sentry = core.app.init_sentry()
  File "/linkr/core/app.py", line 60, in init_sentry
    sentry.init_app(app)
  File "/linkr/env/lib/python2.7/site-packages/raven/contrib/flask.py", line 269, in init
_app
    self.client = make_client(self.client_cls, app, self.dsn)
  File "/linkr/env/lib/python2.7/site-packages/raven/contrib/flask.py", line 50, in make_client
    'app': app,
  File "/linkr/env/lib/python2.7/site-packages/raven/base.py", line 164, in __init__
    self.set_dsn(dsn, transport)
  File "/linkr/env/lib/python2.7/site-packages/raven/base.py", line 233, in set_dsn
    transport_registry=self._registry,
  File "/linkr/env/lib/python2.7/site-packages/raven/conf/remote.py", line 98, in from_string
    raise InvalidDsn(ERR_UNKNOWN_SCHEME.format(url.scheme, value))
raven.exceptions.InvalidDsn: Unsupported Sentry DSN scheme:  (null)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linkr@1.0.0 build-html: `PYTHONPATH=. python scripts/build_html.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linkr@1.0.0 build-html script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-21T23_53_26_979Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linkr@1.0.0 build: `npm run generate-secret && npm run build-css && npm run build-js && npm run build-html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linkr@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-21T23_53_27_001Z-debug.log
Waiting for database....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

Currently at...db loading forever.

**Comment by tiirex9** [comment]
Did you copy the .env.example to .env and entered the necessary data?
I think at least the MySQL credentials are necessary. The npm error seems to have something to do with that. Also explains why linkr can’t connect to the database. 
Don‘t forget to mention the .env file in your docket-compose.yml as an in the provided example. :)

If this does not help I can have a deeper look in approximately 10 hours.

**Comment by TiiFuchs** [comment]
It seems like something changed with the raven stuff...
Please try to set SENTRY_SERVER_DSN and SENTRY_CLIENT_DSN to an empty string in your .env file. That should help. :)

Then run the setup again with `docker-compose run linkr setup`

**Comment by githubbbie** [comment]
Ok, trying:

<img width="249" alt="Screen Shot 2020-02-21 at 9 21 40 PM" src="https://user-images.githubusercontent.com/58287607/75085561-37024000-54f0-11ea-80bf-9d52815da84e.png">

**Comment by githubbbie** [comment]
ok, errors not showing, but does the database loading take this long?

<img width="631" alt="Screen Shot 2020-02-21 at 9 36 18 PM" src="https://user-images.githubusercontent.com/58287607/75085782-4aaea600-54f2-11ea-988f-41650d45a3e3.png">


5-10 min so far...hmmm

**Comment by githubbbie** [comment]
stillllll going, about an hour plus now... any advice? how to diagnose?

**Comment by TiiFuchs** [comment]
You need to adjust the MYSQL_HOST and REDIS_HOST values to the name of the services in your docker-compose.yml

Please read the configuration values carefully.

You may want to change the LINKR_URL setting too. Maybe expose port 5000 from your docker container on your host machine. Then you need to set the port settings in your docker-compose.yml

**Comment by githubbbie** [comment]
ok

In the .env

STATSD_HOST=localhost
STATSD_PORT=8125

What are those? Seems incomplete? What to set to?


Also in the docker-compose.yml why is this set when in the setup screen am asked for root username and password?

  mysql:
    image: mariadb
    volumes:
      - linkr-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes


Ok, making progress... 

THANKS

**Comment by TiiFuchs** [comment]
STATSD is currently not configured, so you can leave the settings. If you want to use it you have to add a corresponding container yourself and change the settings in the .env.

The docker-compose.yml includes the .env file for each mysql and linkr, so both can use the MYSQL_USER, MYSQL_PASSWORD and MYSQL_DATABASE values. mysql creates the user and database accordingly and linkr reads the values to connect.

When you run `docker-compose run linkr setup` your output should come to something like this (with the values in your .evn of course):
<img width="845" alt="CleanShot 2020-02-22 at 14 46 33@2x" src="https://user-images.githubusercontent.com/1958744/75093466-45993780-5582-11ea-9037-5c252b68ff26.png">

But if you started your mysql instance before you configured it correctly it may not try again to create the database. Try deleting the named-volume by running `docker-compose down -v`. When you up it again, it creates everything and it should "just work".

**Comment by githubbbie** [comment]
Who is the admin and admin user? 

<img width="653" alt="Screen Shot 2020-02-22 at 7 53 02 AM" src="https://user-images.githubusercontent.com/58287607/75093571-7fe5e300-5548-11ea-9b37-82776b2cd5e2.png">


(NOTE: I will submit back a PR after I get thru this...thanks!)

**Comment by githubbbie** [comment]
Another one, how can set the LINKR_URL to something like:

LINKR_URL=https://mydomain.com

This is the frontend url, or the url used by the reverse proxy?

I have nginx in front.

**Comment by githubbbie** [comment]
Note for self, on first run: docker-compose up

The database connection fails. After taking down the container and bringing containers back up, the connection works.

**Comment by TiiFuchs** [comment]
> Who is the admin and admin user?

I don't know what you mean...

> This is the frontend url, or the url used by the reverse proxy?

The LINKR_URL should be the url that the users access the service by. So in this case it should be the domain that is configured in your reverse proxy.

> on first run: docker-compose up The database connection fails. 

Then it seems like you did something wrong. The steps for easy installation are
1. Clone the repository
2. Copy the .env.example to .env and change everything you need to change. LINKR_URL, MYSQL_* REDIS_*. (Although I changed the default HOST for mysql and redis so from now on you need to change the hostname only if you changed the service names in your docker-compose.yml).
3. Execute `docker-compose run linkr setup`. This is the most important step since here everything gets configured and compiled. (A process defined by linkr itself, not me.) It takes a whilte to compile, then it waits for the mysql container to accept connections, and then it asks you to press a key. After you did that it shows you the mysql configuration from the .env file. After that you can create your admin user. Enter the username and the password that you want your admin user to have. That's all. (This is the normal process for linkr, this has nothing to do with this dockerized version.)
4. `docker-compose up -d` and you're up to go.

**Comment by githubbbie** [comment]
Ok, got thru and site is running.

Now cannot login or register, which I set to be the default.

```
linkr_1  | [Sun Feb 23 04:41:37.761960 2020] [wsgi:error] [pid 168:tid 140396205529832] [client 172.18.0.3:56438] ResponseError: Client sent AUTH, but no password is set, referer
```
Here is a screenshot of logs tail end...


<img width="630" alt="Screen Shot 2020-02-22 at 10 51 36 PM" src="https://user-images.githubusercontent.com/58287607/75103818-f5dc5f80-55c5-11ea-8380-a002c135b1e9.png">

**Comment by TiiFuchs** [comment]
Did you run the setup and created your admin user? You have to set a username and a password.

**Comment by githubbbie** [comment]
Yes

**Comment by TiiFuchs** [comment]
But you can‘t login with that user or what exactly is your problem?

**Comment by githubbbie** [comment]
I try that user and password entered. And tried after clean install.

The login page freezes then you get that output...

**Comment by TiiFuchs** [comment]
Are there any Docker related problems left? Doesn’t sound like it...?

**Comment by githubbbie** [comment]
Will try again, thanks for all your help
